name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        meteor: [1.12.2, 2.8.1, 2.12, 2.15]
        redis-version: [4, 5, 6, 7]

    steps:
      - uses: actions/checkout@v4

      - name: Start Redis
        uses: supercharge/redis-github-action@1.5.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Setup Meteor
        uses: meteorengineer/setup-meteor@v2
        with:
          meteor-release: ${{ matrix.meteor }}
      - name: Setup tests
        run: |
          meteor create --release ${{ matrix.meteor }} --bare test
          cd test
          meteor npm i --save puppeteer@1.18.1 simpl-schema@1.13.1 chai@4
      - name: Test
        working-directory: ./test
        run: METEOR_PACKAGE_DIRS="../" TEST_BROWSER_DRIVER=puppeteer meteor test-packages --raw-logs --once --driver-package meteortesting:mocha ../
